### ISSUE TITLE
dynamic?

### ISSUE THREAD

**Issue by Psytoshgen** [JuanMTech/macOS-Theme#1]
Hi!
You got one of my favorite themes, they are most nice-looking with Outline (from "you know that man" =))))
Is there any chance to get dynamic theme like macOS? I'm newbie to HA, so try to get info from all corners.
Sorry if I do mistakes, English is not my native language.

Best regards.

**Comment by JuanMTech** [comment]
Sorry, but I didn't understand your question.

**Comment by Psytoshgen** [comment]
> Sorry, but I didn't understand your question.

It would be nice to have dynamic desktop wallpaper from macOS or dynamic desktop app from windows store.
